# Generated by Django 4.2.19 on 2025-04-07 12:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plant_view", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                4, "Name should contain more, than 4 characters."
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="plant",
            name="plant_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plant_view.planttype"
            ),
        ),
    ]
