# Generated by Django 4.2.19 on 2025-04-13 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant_view", "0002_planttype_alter_plant_plant_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                4, "Name should contain more, than 4 characters."
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PlantEvent",
        ),
    ]
